## Naive Bayes Algorithm - Classification of Algorithm
- Based on **Bayes's theorem** of conditional probability
- Calculate the probability of each test point to be in either of classes, given that the features that determine the class are given.
- P(0/x1,x2,x3) and P(1/x1,x2,x3) is calculated, where 0 and 1 are classificcation. x1,x2,x3 are features
- This algorithm assumes 
    - all classes are independent, while its not that true always. However, despite going wrong on basic logic, its still a very strong algorithm.
    - Sequence doesn't matter, while its not true. Like the sequence of words in a sentence do matter for meaning of sentence.
- Eg: In NLP, this is used to understand the tone of text like, 'If this word is present in the sentence, what class it belongs to?'
- Widely used in HAM-SPAM classification
- Very fast algorithm as it simply calculates probability based on features. Very strong results despite assumptions that serve as basis of algorithm are wrong. 
- Technically it processes words and language, so it may be thought as a part of NLP. But since it doens't understand semantics and sentiments of language, it can't handle language processing on its own.
### 3 Types of Naive Bayes in Scikit Learn
__Gaussian__
- It is used in classification and it assumes that features follow a normal distribution.

__Multinominal__
- It is used for discrete counts. For eg., let's say we have a text cLassification problem. Here we consider Bernoulli trails which is one step further and instead of "word occuring in the document", we have "count how often word occurs in the document" you can think of it as "number of times outcome number_x is observed over n trails".

__Bernoulli__
- The binomial model is useful if your feature vectors are binary (ie., Zeroes and One). One application would be text classification with 'bag of words' model where the 1s and 0s are "words occur in the document" and "word does not occur in the document" respectively.

# Text Preprocessing in NLP

# What is Text Preprocessing?

Text preprocessing means:

> Cleaning and converting raw text into a proper format before giving it to a machine learning model.

Computers cannot understand raw text properly.

So we clean and standardize the text.

---

# Why Text Preprocessing is Important?

Real-world text contains:
- Uppercase letters
- Symbols
- Emojis
- Punctuation
- Extra spaces
- Unnecessary words

Example:

```python
"Hello!!! How are you???"
```

Machine learning models may treat:
- `Hello`
- `hello`
- `HELLO`

as different words.

Preprocessing solves this problem.

---

# Main Steps in Text Preprocessing

```text
Raw Text
   ↓
Lowercasing
   ↓
Remove Punctuation
   ↓
Tokenization
   ↓
Remove Stopwords
   ↓
Stemming / Lemmatization
   ↓
Clean Text
```

---

# Step 1: Lowercasing

Convert all text into lowercase.

Example:

Before:

```python
"I LOVE Python"
```

After:

```python
"i love python"
```

Purpose:
- Avoid duplicate words
- Treat all words equally

Without lowercasing:
- `Python`
- `python`

become different words.

---

# Step 2: Remove Punctuation

Remove symbols like:
- `.`
- `!`
- `?`
- `,`

Example:

Before:

```python
"Hello!!!"
```

After:

```python
"Hello"
```

Purpose:
Punctuation usually does not help in prediction.

---

# Step 3: Tokenization

Split sentence into individual words.

Example:

Before:

```python
"I love python"
```

After:

```python
["I", "love", "python"]
```

Each word is called a:
# Token

Purpose:
Machine learning processes words individually.

---

# Step 4: Remove Stopwords

Stopwords are very common words that add little meaning.

Examples:
- is
- am
- the
- are
- was
- and

Example:

Before:

```python
"I am learning data science"
```

After removing stopwords:

```python
["learning", "data", "science"]
```

Purpose:
Reduce unnecessary words.

---

# Step 5: Stemming

Reduce word to root form.

Example:

| Original Word | Stemmed Word |
|---|---|
| playing | play |
| played | play |
| plays | play |

Purpose:
Treat similar words as same word.

---



# Advantages of Text Preprocessing

- Reduces noise
- Improves model accuracy
- Reduces vocabulary size
- Faster training
- Better predictions

---

# Common NLP Applications

- Spam Detection
- Chatbots
- Sentiment Analysis
- Recommendation Systems
- Machine Translation
- Search Engines

In [1]:
import pandas as pd
import numpy as np
import string
df = pd.read_csv("spam.tsv",sep='\t',names=['Class','text'])
df.head()

  Class                                               text
0   ham  I've been searching for the right words to tha...
1  spam  Free entry in 2 a wkly comp to win FA Cup fina...
2   ham  Nah I don't think he goes to usf, he lives aro...
3   ham  Even my brother is not like to speak with me. ...
4   ham               I HAVE A DATE ON SUNDAY WITH WILL!!!

In [2]:
#The csv file being read
import pandas as pd
import numpy as np
import string
df1 = pd.read_csv("spam.csv",encoding='latin1')    #encoding is specified as latin1 because text contains non-unicode characters
df1.head()

   type                                              email
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.shape

(5567, 2)

In [4]:
## The mails are categorised into 2 classes ie., spam and ham.
# Let's see the count of each class
df.groupby('Class').count()

       text
Class
ham    4821
spam    746

## Text preprocessing

In [5]:
df.loc[df['Class']=='spam','Class'] = 1
df.loc[df['Class']=='ham','Class'] = 0
y = df['Class'].values #defining target
y

array([0, 1, 0, ..., 0, 0, 0], dtype=object)

In [6]:
#Strings are sensitive to case and punctuation. So when dealing with strings, we remove punctuations and convert case
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [7]:
# Why is it important to remove punctuation?

"This message is spam" == "This message is spam."

False

In [8]:
def remove(text):
  out=''
  for i in text:
    if i not in string.punctuation:
      out=out+i
  return out

str1="hi.. hello!!"
remove(str1)

'hi hello'

In [9]:
def remove_punc(text):
    return "".join(char for char in text if char not in string.punctuation)
remove_punc('Animals are ,dfd/.,/')

'Animals are dfd'

In [10]:
#Apply this function using 'apply' command or use a for loop
df['cln_txt'] = df['text'].apply(lambda x: remove_punc(x).lower())
df.head()

,Class,text,cln_txt
0,0,I've been searching for the right words to tha...,ive been searching for the right words to than...
1,1,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...
2,0,"Nah I don't think he goes to usf, he lives aro...",nah i dont think he goes to usf he lives aroun...
3,0,Even my brother is not like to speak with me. ...,even my brother is not like to speak with me t...
4,0,I HAVE A DATE ON SUNDAY WITH WILL!!!,i have a date on sunday with will

- Tokenization (process of converting the normal text strings in to a list of tokens(also known as lemmas)).
- Now we need to convert each of those messages into a vector the SciKit Learn's algorithm models can work with and machine learning model which we will gonig to use can understand.

In [11]:
len(df)

5567

In [12]:
type(y)

numpy.ndarray

In [13]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
cv=CountVectorizer(stop_words='english')
# Countvectorizer is a method to convert text to numerical data.
#specifying stop_words='english': Stops adding 'the','a' kind of words in the bag of words, 
#which might end up adding weightages to those words and their probabilities
x = df['cln_txt']
x_vec1 = cv.fit_transform(x)
x_vec = x_vec1.toarray()    #vectorising the words and making it an array.
y = y.astype('int8')  #Type casting y to integer

In [14]:
print(type(x_vec1), type(x_vec))

<class 'scipy.sparse._csr.csr_matrix'> <class 'numpy.ndarray'>

In [15]:
x_vec.shape

(5567, 9270)

In [16]:
x_vec

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_vec,y,test_size=0.2,random_state=42)

In [18]:
print(len(x_train),len(x_test))

4453 1114

In [19]:
from sklearn.naive_bayes import MultinomialNB   #Bernouli's NB is ideal
nb = MultinomialNB()  #Creating instance
nb.fit(x_train,y_train)
y_pred = nb.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 1], dtype=int8)

In [20]:
df.Class.value_counts()

Class
0    4821
1     746
Name: count, dtype: int64

In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99       969
           1       0.88      0.96      0.92       145

    accuracy                           0.98      1114
   macro avg       0.94      0.97      0.95      1114
weighted avg       0.98      0.98      0.98      1114

In [22]:
text= input('Enter a message: ')
#txt = np.array(text)
txt_vec = cv.transform([text])
_pred = nb.predict(txt_vec)
if _pred == 0:
    print('ham')
else:
    print('spam')

Enter a message:  hi..hello

ham

# Bag of Words (BoW)

## What is Bag of Words?

Bag of Words is a technique used in NLP (Natural Language Processing) to convert text into numerical form.

It counts how many times each word appears in a sentence or document.

---

# Example

## Sentences

```python
documents = [
    "I love python",
    "I love coding",
    "python is easy"
]
```

---

# Step 1: Extract All Words

```python
I, love, python,
I, love, coding,
python, is, easy
```

---

# Step 2: Remove Duplicate Words

```python
I, love, python, coding, is, easy
```

---

# Step 3: Convert to Lowercase

`CountVectorizer()` converts all text into lowercase.

```python
i, love, python, coding, is, easy
```

---

# Step 4: Sort Alphabetically

Final vocabulary:

```python
['coding', 'easy', 'is', 'love', 'python']
```

---

# Step 5: Create BoW Matrix

| Sentence | coding | easy | is | love | python |
|---|---|---|---|---|---|
| I love python | 0 | 0 | 0 | 1 | 1 |
| I love coding | 1 | 0 | 0 | 1 | 0 |
| python is easy | 0 | 1 | 1 | 0 | 1 |

---

---

In [23]:

# Bag of words
from sklearn.feature_extraction.text import CountVectorizer

docs = [
    "I love python",
    "I love coding"
]

cv = CountVectorizer()

X = cv.fit_transform(docs)

print(cv.get_feature_names_out())
print(X.toarray())

['coding' 'love' 'python']
[[0 1 1]
 [1 1 0]]



```python
[0 0 0 1 1]
```

Meaning:

| Word | Count |
|---|---|
| coding | 0 |
| easy | 0 |
| is | 0 |
| love | 1 |
| python | 1 |

Sentence:

```python
"I love python"
```